### PR TITLE
Add info on DISQUS, SITEMAP and GA

### PR DESCRIPTION
**Pull request by iranzo**
Adds information on how to setup DISQUS, SITEMAP and GA in your pelican/blue-penguin site

### CODE REVIEW

**Comment by jody-frankowski** [comment]
@jorgesumle Why the thumb down?

**Comment by jorgesumle** [comment]
>  # sitemap for google 

Sitemap is not "for Google", it's for almost every search engine. 

Also, I don't like Google Analytics and Disqus because they are proprietary.

**Comment by iranzo** [comment]
The templates are already in the code (disqus) for example you're open to use them or not.

**Comment by jody-frankowski** [comment]
I agree with both of you. While they're proprietary systems, they're already in the templates and I can't stop people from using them.
@iranzo If you could change the sitemap phrasing to be more generic, I'll merge the PR :)

**Pull request closed without merging**
